spring:
  security:
    oauth2:
      client:
#        The ${} placeholders will be replaced with environment variables that we specify
#        when deploying our Todo application with ECS (using SpEL - Spring’s powerful expression language).
        registration:
          cognito:
            client-id: ${COGNITO_CLIENT_ID}
            client-secret: ${COGNITO_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          cognito:
            issuer-uri: ${COGNITO_PROVIDER_URL}

custom:
  sharing-queue: ${TODO_SHARING_QUEUE_NAME}
  web-socket-relay-endpoint: ${WEB_SOCKET_RELAY_ENDPOINT}
  web-socket-relay-username: ${WEB_SOCKET_RELAY_USERNAME}
  web-socket-relay-password: ${WEB_SOCKET_RELAY_PASSWORD}
  web-socket-relay-use-ssl: true
  use-cognito-as-identity-provider: true
