spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: test
    password: test
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: spring-boot-application
            client-secret: 27b07baf-53ba-42c6-b11f-6384769cada3
            scope:
              - openid
        provider:
          cognito:
            issuer-uri: http://localhost:8888/auth/realms/todo-app
  cloud:
    aws:
      credentials:
        access-key: bar
        secret-key: foo
      endpoint: http://localhost:4566
      region:
        static: us-west-1

custom:
  auto-confirm-collaborations: true
  use-cognito-as-identity-provider: false
